---
application:
  name: "chatcord"
  project: "hangout-v2"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 8080
routers:
- name: "main-chatcord"
  routes:
  - application_name: "chatcord"
    paths:
    - "/*"
